include /root/softwarePlatform/common/mmslite-6.0000/mmslite-client.mk

CC_TARGET    = libsmms_client.a
CC_TARGET_D  = libsmms_clientd.a
INSTALL_PATH = ../../lib/linux
FIS_MMSCLT_PATH = /root/UK9001/src/fis_mmsclt

RM = rm -rf
LN = ln
CP = cp -f
MV = mv

SRCS =  \
	client.c \
	cli_rpt.c \
	clntobj.c \
	event.c \
	logcfgx.c \
	mmsop_en.c \
	mvl_acse.c \
	SMmsClient.cpp \
	utf2gb.cpp

OBJS =  *.o 

all:
		$(RM) debug
		$(CC) -c $(SRCS) $(CC_INCLUDES) $(CC_COMPLIE)
		$(AR) $(CC_TARGET) $(OBJS)
		$(RM) *.o
		$(CC) -c mvlop_en.c reject.c $(CC_INCLUDES) $(CC_COMPILE)
		$(MV) mvlop_en.o reject.o $(FIS_MMSCLT_PATH)/
		$(CP) $(CC_TARGET) $(INSTALL_PATH)/

debug:
		$(RM) debug
		$(CC) -c $(SRCS) $(CC_INCLUDES) $(CC_COMPLIE_D)
		$(AR) $(CC_TARGET_D) $(OBJS)
		$(RM) *.o
		$(CC) -c mvlop_en.c reject.c $(CC_INCLUDES) $(CC_COMPILE_D)
		$(MV) mvlop_en.o $(FIS_MMSCLT_PATH)/mvlop_en_d.o
		$(MV) reject.o $(FIS_MMSCLT_PATH)/reject_d.o
		$(CP) $(CC_TARGET_D) $(INSTALL_PATH)/

clean:
		$(RM) *.o
		$(RM) *.d

install:
		$(CP) $(CC_TARGET) $(INSTALL_PATH)/$(CC_TARGET)
		$(CP) $(CC_TARGET_D) $(INSTALL_PATH)/$(CC_TARGET_D)
