# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../include/ssp_iaFloatView/ssp_iafloatview.h \
    ../../src/ssp_iaFloatView/dlgmessage.h \
    ../../src/ssp_iaFloatView/dlgconfigure.h \
    ../../src/ssp_iaFloatView/cfloatviewmenu.h \
    ../../src/ssp_iaFloatView/cia2alarmpopwnd.h
SOURCES += ../../src/ssp_iaFloatView/cfloatviewmenu.cpp \
    ../../src/ssp_iaFloatView/cia2alarmpopwnd.cpp \
    ../../src/ssp_iaFloatView/dlgconfigure.cpp \
    ../../src/ssp_iaFloatView/dlgmessage.cpp \
    ../../src/ssp_iaFloatView/ssp_iafloatview.cpp
FORMS += ../../src/ssp_iaFloatView/cia2alarmpopwnd.ui \
    ../../src/ssp_iaFloatView/dlgmessage.ui \
    ../../src/ssp_iaFloatView/dlgconfigure.ui
RESOURCES += ../../src/ssp_iaFloatView/ssp_iaFloatView.qrc
