# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = ssp_iaFloatView
QT += core gui
DEFINES += QT_DLL _IA2_STYLE_ SSP_FLOAT_WND_EXPORT_DLL
INCLUDEPATH += ./GeneratedFiles \
    . \
    ./GeneratedFiles/Release \
    ./../../src/ssp_iaFloatView
	
include(./ssp_iaFloatView.pri)
DEPENDPATH += .
UI_DIR += ssp_iaFloatView/GeneratedFiles
RCC_DIR += ssp_iaFloatView/GeneratedFiles

CONFIG(debug, debug|release) {
	TARGET = ssp_iaFloatViewd
	MOC_DIR += ssp_iaFloatView/GeneratedFiles/debug
	OBJECTS_DIR += ssp_iaFloatView/debug
} else {
	TARGET = ssp_iaFloatView
	MOC_DIR += ssp_iaFloatView/GeneratedFiles/release
	OBJECTS_DIR += ssp_iaFloatView/release
}

unix {	
	LIBS += -L/opt/instantclient_12_1
	INCLUDEPATH += /home/SoftwarePlatform/sbase/include \
		/home/SoftwarePlatform/sbase/include/comm \
		/home/SoftwarePlatform/sbase/include/db \
		/home/SoftwarePlatform/sbase/include/db/mysql \
		/home/SoftwarePlatform/sbase/include/db/oracle \
		/home/SoftwarePlatform/sbase/include/db/mdb \
		/home/SoftwarePlatform/sbase/include/gui \
		/home/SoftwarePlatform/sbase/include/gui/qt \
		/home/SoftwarePlatform/sbase/include/gui/svg \
		/home/SoftwarePlatform/SSP01/include/ssp_base \
		/home/SoftwarePlatform/SSP01/include/ssp_gui \
		/opt/instantclient_12_1/sdk/include \
		/usr/include \
		/usr/include/mysql \
		/usr/local/include \
		../../include/ssp_iaFloatView
	
	exists( /etc/debian_version ) {
		LIBS += -L/home/SoftwarePlatform/sbase/lib/linux-debian -L/home/SoftwarePlatform/SSP01/lib/linux-debian
        DESTDIR = ../../lib/linux-debian
    } else:exists( /etc/redhat-release ) {
		LIBS += -L/home/SoftwarePlatform/sbase/lib/linux-redhat -L/home/SoftwarePlatform/SSP01/lib/linux-redhat
        DESTDIR = ../../lib/linux-redhat
    } else {
		LIBS += -L/home/SoftwarePlatform/sbase/lib/linux -L/home/SoftwarePlatform/SSP01/lib/linux
		DESTDIR = ../../lib/linux
	}
}

win32 {
	DESTDIR = ../../lib/win32
}
