# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = ssp_gui

QT += core gui webkit
DEFINES += QT_DLL SSP_GUI_LIB QT_WEBKIT_LIB
INCLUDEPATH += ./GeneratedFiles \
    . \
    ./GeneratedFiles/Release \
    ./../../src/ssp_gui
	
UI_DIR += ssp_gui/GeneratedFiles
RCC_DIR += ssp_gui/GeneratedFiles
	
CONFIG(debug, debug|release) {
	TARGET = ssp_guid
	MOC_DIR += ssp_gui/GeneratedFiles/debug
	OBJECTS_DIR += ssp_gui/debug
} else {
	TARGET = ssp_gui
	MOC_DIR += ssp_gui/GeneratedFiles/release
	OBJECTS_DIR += ssp_gui/release
}

unix {	
	LIBS += -L/opt/instantclient_12_1
	INCLUDEPATH += /home/SoftwarePlatform/sbase/include \
		/home/SoftwarePlatform/sbase/include/comm \
		/home/SoftwarePlatform/sbase/include/db \
		/home/SoftwarePlatform/sbase/include/db/mysql \
		/home/SoftwarePlatform/sbase/include/db/oracle \
		/home/SoftwarePlatform/sbase/include/db/mdb \
		/home/SoftwarePlatform/sbase/include/gui \
		/home/SoftwarePlatform/sbase/include/gui/qt \
		/home/SoftwarePlatform/sbase/include/gui/svg \
		/home/SoftwarePlatform/SSP01/include/ssp_base \
		/home/SoftwarePlatform/SSP01/include/ssp_gui \
		/opt/instantclient_12_1/sdk/include \
		/usr/include \
		/usr/include/mysql \
		/usr/local/include
	
	exists( /etc/debian_version ) {
		LIBS += -L/home/SoftwarePlatform/sbase/lib/linux-debian -L/home/SoftwarePlatform/SSP01/lib/linux-debian
        DESTDIR = ../../lib/linux-debian
    } else:exists( /etc/redhat-release ) {
		LIBS += -L/home/SoftwarePlatform/sbase/lib/linux-centos -L/home/SoftwarePlatform/SSP01/lib/linux-centos
        DESTDIR = ../../lib/linux-centos
    } else {
		LIBS += -L/home/SoftwarePlatform/sbase/lib/linux -L/home/SoftwarePlatform/SSP01/lib/linux
		DESTDIR = ../../lib/linux
	}
}

win32 {
	DESTDIR = ../../lib/win32
}

DEPENDPATH += .

include(ssp_gui.pri)
